const clientes  = [
  { nombreCliente: 'Carlos', apellidoCliente: 'Ramírez', email: 'carlos.ramirez@example.com', whatsApp: '+573108451201' },
  { nombreCliente: 'María', apellidoCliente: 'Fernández', email: 'maria.fernandez@example.com', whatsApp: '+573102334501' },
  { nombreCliente: 'Juan', apellidoCliente: 'Gómez', email: 'juan.gomez@example.com', whatsApp: '+573102889744' },
  { nombreCliente: 'Ana', apellidoCliente: 'Cárdenas', email: 'ana.cardenas@example.com', whatsApp: '+573106780230' },
  { nombreCliente: 'Luis', apellidoCliente: 'Mendoza', email: 'luis.mendoza@example.com', whatsApp: '+573104556320' },
  { nombreCliente: 'Laura', apellidoCliente: 'Soto', email: 'laura.soto@example.com', whatsApp: '+573103221459' },
  { nombreCliente: 'David', apellidoCliente: 'Pérez', email: 'david.perez@example.com', whatsApp: '+573105990122' },
  { nombreCliente: 'Carolina', apellidoCliente: 'Ríos', email: 'carolina.rios@example.com', whatsApp: '+573108332147' },
  { nombreCliente: 'Andrés', apellidoCliente: 'Vargas', email: 'andres.vargas@example.com', whatsApp: '+573107450998' },
  { nombreCliente: 'Daniela', apellidoCliente: 'Martínez', email: 'daniela.martinez@example.com', whatsApp: '+573101556783' },
  { nombreCliente: 'Felipe', apellidoCliente: 'Torres', email: 'felipe.torres@example.com', whatsApp: '+573102443678' },
  { nombreCliente: 'Valentina', apellidoCliente: 'Guerrero', email: 'valentina.guerrero@example.com', whatsApp: '+573105873442' },
  { nombreCliente: 'Santiago', apellidoCliente: 'Castaño', email: 'santiago.castano@example.com', whatsApp: '+573108774532' },
  { nombreCliente: 'Camila', apellidoCliente: 'Mejía', email: 'camila.mejia@example.com', whatsApp: '+573106432210' },
  { nombreCliente: 'Nicolás', apellidoCliente: 'Herrera', email: 'nicolas.herrera@example.com', whatsApp: '+573104112998' },
  { nombreCliente: 'Diana', apellidoCliente: 'Lozano', email: 'diana.lozano@example.com', whatsApp: '+573103889211' },
  { nombreCliente: 'Julián', apellidoCliente: 'Moreno', email: 'julian.moreno@example.com', whatsApp: '+573102990011' },
  { nombreCliente: 'Sara', apellidoCliente: 'Patiño', email: 'sara.patino@example.com', whatsApp: '+573108223400' },
  { nombreCliente: 'Ricardo', apellidoCliente: 'Gutiérrez', email: 'ricardo.gutierrez@example.com', whatsApp: '+573101883221' },
  { nombreCliente: 'Adriana', apellidoCliente: 'Arango', email: 'adriana.arango@example.com', whatsApp: '+573104667890' },
  { nombreCliente: 'Esteban', apellidoCliente: 'Salazar', email: 'esteban.salazar@example.com', whatsApp: '+573105421001' },
  { nombreCliente: 'Luisa', apellidoCliente: 'Ospina', email: 'luisa.ospina@example.com', whatsApp: '+573102334900' },
  { nombreCliente: 'Tomás', apellidoCliente: 'Rendón', email: 'tomas.rendon@example.com', whatsApp: '+573108112778' },
  { nombreCliente: 'Isabela', apellidoCliente: 'Berrío', email: 'isabela.berrio@example.com', whatsApp: '+573106225990' },
  { nombreCliente: 'Mateo', apellidoCliente: 'Álvarez', email: 'mateo.alvarez@example.com', whatsApp: '+573103210554' },
  { nombreCliente: 'Paula', apellidoCliente: 'Giraldo', email: 'paula.giraldo@example.com', whatsApp: '+573101332745' },
  { nombreCliente: 'Sebastián', apellidoCliente: 'Roldán', email: 'sebastian.roldan@example.com', whatsApp: '+573102998311' },
  { nombreCliente: 'Manuela', apellidoCliente: 'Cifuentes', email: 'manuela.cifuentes@example.com', whatsApp: '+573108890011' },
  { nombreCliente: 'Cristian', apellidoCliente: 'Henao', email: 'cristian.henao@example.com', whatsApp: '+573104556789' },
  { nombreCliente: 'Karen', apellidoCliente: 'Zapata', email: 'karen.zapata@example.com', whatsApp: '+573103445622' },
  { nombreCliente: 'Miguel', apellidoCliente: 'Quintero', email: 'miguel.quintero@example.com', whatsApp: '+573102889900' },
  { nombreCliente: 'Alejandra', apellidoCliente: 'Correa', email: 'alejandra.correa@example.com', whatsApp: '+573105553210' },
  { nombreCliente: 'Óscar', apellidoCliente: 'Montoya', email: 'oscar.montoya@example.com', whatsApp: '+573101229944' },
  { nombreCliente: 'Natalia', apellidoCliente: 'Pérez', email: 'natalia.perez@example.com', whatsApp: '+573106783421' },
  { nombreCliente: 'Hernán', apellidoCliente: 'Bedoya', email: 'hernan.bedoya@example.com', whatsApp: '+573108399112' },
  { nombreCliente: 'Marcela', apellidoCliente: 'Murillo', email: 'marcela.murillo@example.com', whatsApp: '+573104556221' },
  { nombreCliente: 'Diego', apellidoCliente: 'Yepes', email: 'diego.yepes@example.com', whatsApp: '+573103221784' },
  { nombreCliente: 'Verónica', apellidoCliente: 'Montes', email: 'veronica.montes@example.com', whatsApp: '+573102456900' },
  { nombreCliente: 'Jorge', apellidoCliente: 'Londoño', email: 'jorge.londono@example.com', whatsApp: '+573108112456' },
  { nombreCliente: 'Fabiola', apellidoCliente: 'Tobón', email: 'fabiola.tobon@example.com', whatsApp: '+573106891234' },
  { nombreCliente: 'Samuel', apellidoCliente: 'Cano', email: 'samuel.cano@example.com', whatsApp: '+573105900442' },
  { nombreCliente: 'Melisa', apellidoCliente: 'Hurtado', email: 'melisa.hurtado@example.com', whatsApp: '+573103229900' },
  { nombreCliente: 'Iván', apellidoCliente: 'Porras', email: 'ivan.porras@example.com', whatsApp: '+573102341110' },
  { nombreCliente: 'Gloria', apellidoCliente: 'Sierra', email: 'gloria.sierra@example.com', whatsApp: '+573108320550' },
  { nombreCliente: 'Henry', apellidoCliente: 'Gómez', email: 'henry.gomez@example.com', whatsApp: '+573104452210' }
]



export default clientes;